### PR TITLE
Explain how to install outputlilypond for development

### PR DESCRIPTION
**Pull request by maxalbert**
This PR adds information how to install `outputlilypond`. I have only added this to the development section so far as I'm not sure how this can (or even whether it should) be handled with regular installs via pip.

### CODE REVIEW

**Comment by crantila** [comment]
Thanks for your PR, which shouldn't have any impact on the Travis-CI issue. I like the solution you propose, and even how you describe it, but it might make more sense to make the PR onto the devel_docs branch. Depends what Ryan says about that.

In any case, I think this is now the prompt for me to finally finish and merge devel_docs. Even if Ryan accepts this PR, I'll be sure to cherry-pick it to devel_docs!

**Comment by crantila** [comment]
Oh, an additional thing about ``outputlilypond`` that @mrbannon and @ahankinson probably want to think/know about. For VIS releases on PyPI, I was distributing both "vis-framework" and "outputlilypond" in the same "vis-framework" package, because I wanted to retire outputlilypond in favour of migrating its functionality upstream to music21's LilyPond exporting capability.

Now that the future of LilyPond in music21 is generally in question, I'm not sure of the best course of action. Would you like me to post ``outputlilypond`` to PyPI as an independent package, so it can be "included" properly, for as long as it still works?

**Comment by maxalbert** [comment]
@crantila Thanks for the prompt reply! I only just noticed the failing Travis CI build, but as you say it seems to be unrelated to my change and appears to have already been fixed in Ryan's dev branch. Regarding the documentation, feel free to close this PR in case it's more appropriate to apply it directly to devel_docs. I'm happy to submit a PR against that branch instead (but haven't done it yet because I wasn't sure how outdated it was and whether it would require significant rebasing).

**Comment by crantila** [comment]
Good point. I'll check on that within the next couple of days and let you know what seems better. I could just make the changes myself of course, but if you do a PR you can have the credit in the repository for finding and fixing the issue.

**Pull request merged**
